### ISSUE TITLE
How to center the map to the multipoint ?

### ISSUE THREAD

**Issue by xoco70** [davidpiesse/nova-map#26]
I have the trait in my model, I can see the maps, I can see the multipoint, but I can't start the map centered.

            Map::make('Multipoint', 'multi')
                ->spatialType('Multipoint');

I have tried to use longitude() and latitude() but it doesn't work.

How should I center a single point may be a good place to start.

I use Laravel 6 / Nova 2

**Comment by davidpiesse** [comment]
Right now I don't believe there is a method to center the map. You are more than welcome to pr one in. It certainly makes sense to have that option.

**Comment by xoco70** [comment]
OK, but... so you mean my only option ingstart see the null island and then move the map to my points ? I think I am missing something.

**Comment by davidpiesse** [comment]
OK,
Slightly diff issue than I thought - sorry on that.

MapDetail.js
```js
  mounted() {
            this.$nextTick(() => {
                this.map = this.$refs.map.mapObject
                this.geojsonLayer = this.$refs.geojsonLayer.mapObject
                this.setCenter()
            })
        },
        methods: {
            setCenter() {
                if (this.geojson !== null) {
                    this.map.fitBounds(L.geoJSON(this.geojson).getBounds(), {maxZoom: 18}).setZoom(this.zoom)
                }
            },
        }
```

If you are uploading a multipoint it should be converted to geojson.

So it should come across (as it does if you see it) - then the map is fitted to the bounds / extent of those geometries. If it is not centering - then this bit of code is not working.

If you could dig into this a little bit that would be awesome to see where the issue is.

**Comment by xoco70** [comment]
Yes ! Thanks for your help, I'll tell you if I can find something ! I'm not very good at VueJS, but I am sure I can do something about it
